const SUPABASE_URL='https://bjxbqhcgdwmluwjfawse.supabase.co';
const SUPABASE_KEY='sb_publishable_Pba7tiTGZFh3lo-AcVitlA_6E-WA5ZJ';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const ADMIN_EMAIL='info@smartfitout.in';
let type='quotation',items=[];
const $=id=>document.getElementById(id);
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
async function login(){const email=$('email').value.trim().toLowerCase();const password=$('password').value;if(email!==ADMIN_EMAIL){$('loginError').textContent='Use the Smart Fitout admin email.';return}if(!password){$('loginError').textContent='Enter your password.';return}$('loginError').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginError').textContent=error.message;return}showApp()}
async function logout(){await sb.auth.signOut();location.reload()}
async function showApp(){const {data:{user}}=await sb.auth.getUser();if(!user||user.email.toLowerCase()!==ADMIN_EMAIL){await sb.auth.signOut();if($('login')){$('login').hidden=false;$('app').hidden=true}return}if($('login'))$('login').hidden=true;if($('app'))$('app').hidden=false;if($('docDate'))$('docDate').value=new Date().toISOString().slice(0,10);if(typeof newNumber==='function')newNumber();await prefillFromBooking();if(!items.length&&$('items'))addItem();if(typeof renderHistory==='function')renderHistory()}
async function prefillFromBooking(){const bookingId=new URLSearchParams(location.search).get('booking');if(!bookingId)return;const {data:b,error}=await sb.from('service_requests').select('id,customer_name,phone,customer_email,location,description,preferred_date,preferred_time,quoted_amount,services(name)').eq('id',Number(bookingId)).single();if(error||!b)return;$('customerName').value=b.customer_name||'';$('customerMobile').value=b.phone||''; if($('customerEmail'))$('customerEmail').value=b.customer_email||'';$('customerAddress').value=b.location||'';window.SMART_FITOUT_BOOKING_ID=String(b.id);const label=b.services?.name||'Service';const rate=Number(b.quoted_amount||0);items=[{description:label,qty:1,unit:'Job',rate}];renderItems();if($('notes')&&!$('notes').value)$('notes').value=`Service booking #${b.id}${b.description?' — '+b.description:''}`}
function setType(t){type=t;$('docType').value=t;$('qtab').classList.toggle('active',t==='quotation');$('itab').classList.toggle('active',t==='invoice');newNumber()}
function newNumber(){const prefix=type==='quotation'?'QT':'INV';const year=new Date().getFullYear();const n=Number(localStorage.getItem('sf_'+prefix)||0)+1;if($('docNo'))$('docNo').value=`${prefix}-${year}-${String(n).padStart(4,'0')}`}
function addItem(data={description:'',qty:1,unit:'Nos',rate:0}){items.push(data);renderItems()}
function renderItems(){const box=$('items');if(!box)return;box.innerHTML=items.map((x,i)=>`<div class="item"><label>Description<input value="${esc(x.description)}" oninput="items[${i}].description=this.value"></label><label>Qty<input type="number" min="0" step="0.01" value="${x.qty}" oninput="items[${i}].qty=+this.value;calc()"></label><label>Unit<input value="${esc(x.unit)}" oninput="items[${i}].unit=this.value"></label><label>Rate<input type="number" min="0" step="0.01" value="${x.rate}" oninput="items[${i}].rate=+this.value;calc()"></label><button type="button" class="remove" onclick="items.splice(${i},1);renderItems();calc()">×</button></div>`).join('');calc()}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function calc(){const sub=items.reduce((a,x)=>a+(Number(x.qty)||0)*(Number(x.rate)||0),0);const discount=Math.min(Number($('discount')?.value)||0,sub);const taxable=sub-discount;const gst=taxable*(Number($('gst')?.value)||0)/100;const total=taxable+gst;if($('subtotal'))$('subtotal').textContent=money(sub);if($('gstAmount'))$('gstAmount').textContent=money(gst);if($('grandTotal'))$('grandTotal').textContent=money(total);if($('discountView'))$('discountView').textContent=money(discount);return{sub,discount,gst,total}}
function payload(){const c=calc();return{doc_type:type,document_number:$('docNo').value,customer_name:$('customerName').value,customer_mobile:$('customerMobile').value,customer_email:$('customerEmail')?.value.trim().toLowerCase()||'',customer_address:$('customerAddress').value,document_date:$('docDate').value,items,subtotal:c.sub,discount:c.discount,gst_percent:Number($('gst').value)||0,gst_amount:c.gst,total:c.total,payment_status:$('paymentStatus').value,notes:$('notes').value,service_request_id:window.SMART_FITOUT_BOOKING_ID||''}}
async function saveDocument(e){e.preventDefault();const {data:{user}}=await sb.auth.getUser();if(!user||user.email.toLowerCase()!==ADMIN_EMAIL){alert('Admin session expired. Please log in again.');return false}const d=payload();if(!d.customer_name||!items.some(x=>x.description)){alert('Please enter customer name and at least one item.');return false}try{const {error}=await sb.rpc('save_smart_fitout_document',{p_doc:d});if(error)throw error;localStorage.setItem('sf_'+(type==='quotation'?'QT':'INV'),Number(localStorage.getItem('sf_'+(type==='quotation'?'QT':'INV'))||0)+1);const pdf=makePDF(d);saveLocal(d);renderHistory();sharePDF(pdf,d);return false}catch(err){console.error(err);alert('Could not save document. PDF can still be generated. '+err.message);const pdf=makePDF(d);saveLocal(d);renderHistory();sharePDF(pdf,d);return false}}
function saveLocal(d){const a=JSON.parse(localStorage.getItem('sf_docs')||'[]');a.unshift({...d,savedAt:new Date().toISOString()});localStorage.setItem('sf_docs',JSON.stringify(a.slice(0,50)));if($('docCount'))$('docCount').textContent=a.length}
function renderHistory(){const a=JSON.parse(localStorage.getItem('sf_docs')||'[]');if($('docCount'))$('docCount').textContent=a.length;if($('history'))$('history').innerHTML=a.length?a.slice(0,10).map((d,i)=>`<div class="doc"><div><b>${d.document_number}</b> · ${d.doc_type}<br><small>${esc(d.customer_name)} · ${money(d.total)}</small></div><button onclick="sharePDF(makePDF(JSON.parse(localStorage.getItem('sf_docs'))[${i}]),JSON.parse(localStorage.getItem('sf_docs'))[${i}])">Share PDF</button></div>`).join(''):'<small>No documents yet.</small>'}
function makePDF(d){const {jsPDF}=window.jspdf;const pdf=new jsPDF();const W=210;pdf.setFillColor(244,123,32);pdf.rect(0,0,W,8,'F');pdf.setFontSize(22);pdf.setFont('helvetica','bold');pdf.text('SMART FITOUT',18,25);pdf.setFontSize(10);pdf.setFont('helvetica','normal');pdf.text('Your Trusted Maintenance Partner in Udupi',18,32);pdf.text('Udupi, Karnataka, India | +91 96069 63170',18,39);pdf.text('info@smartfitout.in | smartfitout.in',18,45);pdf.setFontSize(18);pdf.setFont('helvetica','bold');pdf.text(d.doc_type==='quotation'?'QUOTATION':'INVOICE',145,27);pdf.setFontSize(10);pdf.setFont('helvetica','normal');pdf.text(d.document_number,145,34);pdf.text(d.document_date,145,40);pdf.line(18,51,192,51);pdf.setFont('helvetica','bold');pdf.text('BILL TO',18,62);pdf.setFont('helvetica','normal');pdf.text(d.customer_name,18,69);if(d.customer_mobile)pdf.text('Mobile: '+d.customer_mobile,18,75);if(d.customer_address)pdf.text(String(d.customer_address).slice(0,95),18,81);let y=96;pdf.setFillColor(21,21,21);pdf.rect(18,y-7,174,9,'F');pdf.setTextColor(255,255,255);pdf.setFont('helvetica','bold');pdf.text('Description',22,y);pdf.text('Qty',116,y);pdf.text('Unit',137,y);pdf.text('Rate',158,y);pdf.text('Amount',178,y);pdf.setTextColor(21,21,21);pdf.setFont('helvetica','normal');y+=9;d.items.forEach(x=>{if(y>265){pdf.addPage();y=20}const amt=(Number(x.qty)||0)*(Number(x.rate)||0);pdf.text(String(x.description).slice(0,45),22,y);pdf.text(String(x.qty),116,y);pdf.text(String(x.unit).slice(0,10),137,y);pdf.text(money(x.rate),158,y);pdf.text(money(amt),178,y);y+=8;});y+=5;pdf.line(125,y,192,y);pdf.text('Subtotal',145,y+8);pdf.text(money(d.subtotal),178,y+8);if(d.discount){pdf.text('Discount',145,y+16);pdf.text('- '+money(d.discount),178,y+16)}pdf.text(`GST (${d.gst_percent}%)`,145,y+24);pdf.text(money(d.gst_amount),178,y+24);pdf.setFont('helvetica','bold');pdf.text('Grand Total',145,y+34);pdf.text(money(d.total),178,y+34);pdf.setFont('helvetica','normal');pdf.text('Payment Status: '+d.payment_status,18,y+34);if(d.notes){pdf.setFont('helvetica','bold');pdf.text('Notes / Terms',18,y+54);pdf.setFont('helvetica','normal');const lines=pdf.splitTextToSize(d.notes,174);pdf.text(lines,18,y+61)}pdf.setFontSize(9);pdf.setTextColor(100,100,100);pdf.text('Thank you for choosing Smart Fitout.',18,285);return pdf}
function sharePDF(pdf,d){const blob=pdf.output('blob');const file=new File([blob],d.document_number+'.pdf',{type:'application/pdf'});if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){navigator.share({title:d.document_number,text:'Smart Fitout '+(d.doc_type==='quotation'?'Quotation':'Invoice'),files:[file]}).catch(()=>{})}else{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);if(d.customer_mobile){setTimeout(()=>window.open('https://wa.me/'+d.customer_mobile.replace(/\D/g,'')+'?text='+encodeURIComponent('Dear '+d.customer_name+', please find your Smart Fitout '+(d.doc_type==='quotation'?'quotation':'invoice')+' '+d.document_number+'.'), '_blank'),500)}}}
function previewPDF(){const d=payload();const pdf=makePDF(d);window.open(URL.createObjectURL(pdf.output('blob')),'_blank')}
sb.auth.getSession().then(({data:{session}})=>{if(session)showApp()});
sb.auth.onAuthStateChange((_event,session)=>{if(session)showApp();});